
#ifndef _ERRORS_H_
#define _ERRORS_H_

#define SAC_OK                               0

#define ERROR_ZOPENC_INSUFFICIENT_ACCESS     1
#define ERROR_ZOPENC_ERROR                   2

#define ERROR_OPENING_FILE                   101
#define ERROR_CREATING_FILE                  102
#define ERROR_HEADER_FORMAT                  106
#define ERROR_FILE_DOES_NOT_EXIST            108
#define ERROR_FILE_ALREADY_EXISTS            109
#define ERROR_READING_FILE                   114
#define ERROR_WRITING_FILE                   115
#define ERROR_NO_WFDISC_FILE_SPECIFIED       120
#define ERROR_ENCODING_XDR_FILE              121
#define ERROR_WRITING_XDR_FILE               122
#define ERROR_BADLY_FORMATTED_CSSPICKSPREFS  125
#define ERROR_WFDISC_FILE_REQUIRES_A_PERIOD  126

#define ERROR_OUT_OF_MEMORY                  301

#define ERROR_SAC_FILE_NOT_EVENLY_SPACED     801
#define ERROR_SAC_FILE_NOT_UNEVENLY_SPACED   802
#define ERROR_SAC_DATA_TRUNCATED_ON_READ     803

#define ERROR_SAC_LOGIC_ERROR                901
#define ERROR_IN_TIME_FIELD                  907
#define ERROR_ILLEGAL_BASE_NAME              914
#define ERROR_FILE_NAME_TOO_LONG             916

#define ERROR_DELIMITER_FOUND_IN_ENTRY       920
#define ERROR_CHARACER_LIST_EXCEED_BOUNDS    921
#define ERROR_NOT_FOUND_IN_RANGE_T0_T9       923

#define ERROR_BAD_COMMAND_SYNTAX            1001
#define ERROR_COMMAND_STACK_OVERRUN         1007
#define ERROR_COMMAND_FILE_MISSING          1008
#define ERROR_TOO_MANY_COMMAND_ARGUMENTS    1009
#define ERROR_WRONG_NUMBER_OF_ARGUMENTS     1010
#define ERROR_COMMAND_FILE_SYNTAX           1011
#define ERROR_EXCEEDED_NUMEBER_OF_COMMANDS  1027
#define ERROR_COMMAND_DOES_NOT_EXIST        1028

#define ERROR_EXECUTING_SYSTEM_COMMAND      1111

#define ERROR_FINDING_VARIABLE              1201
#define ERROR_FINDING_VARIABLE_GROUP        1203
#define ERROR_VARIABLE_TYPE_INCORRECT       1204
#define ERROR_DELETING_VARIABLE             1205

#define ERROR_RMS_NOISE_GREATER_THAN_SIGNAL 1234

#define ERROR_NO_DATA_FILES_READ_IN         1301
#define ERROR_OVERWRITE_FLAG_IS_OFF         1303
#define ERROR_OPERATION_ON_TIME_SERIES_FILE 1305
#define ERROR_OPERATION_ON_UNEVEN_FILE      1306
#define ERROR_OPERATION_ON_SPECTRAL_FILE    1307

#define ERROR_ILLEGAL_DATA_FILE_LIST_NUMBER 1310
#define ERROR_ILLEGAL_RELATIVE_TIME_PICK    1313
#define ERROR_NOT_A_SAC_FILE                1317
#define ERROR_HEADER_OUT_OF_DATE            1318
#define ERROR_READING_CARD_IMAGE_HEADER     1319
#define ERROR_CANT_CUT_SPECTRAL_FILE        1321
#define ERROR_UNDEFINED_START_CUT_TIME      1322
#define ERROR_UNDEFINED_STOP_CUT_TIME       1323
#define ERROR_START_TIME_LESS_THAN_BEGIN    1324
#define ERROR_STOP_TIME_GREATER_THAN_END    1325
#define ERROR_START_TIME_GREATER_THAN_END   1326
#define ERROR_STOP_TIME_LESS_THAN_BEGIN     1327
#define ERROR_START_TIME_GREATER_THAN_STOP  1328
#define ERROR_CORRECTED_BY_FILL_WITH_ZEROS  1329
#define ERROR_CORRECTED_BY_USING_BEGIN_TIME 1330
#define ERROR_CORRECTED_BY_USING_END_TIME   1331
#define ERROR_UNABLE_TO_READ_SOME_FILES     1333
#define ERROR_ONLY_HEADERS_IN_MEMORY        1335
#define ERROR_UNDEFINED_HEADER_FIELD_VALUE  1336
#define ERROR_ILLEGAL_HEADER_FIELD_NAME     1337
#define ERROR_TOO_MANY_DATA_POINTS          1338
#define ERROR_TOO_FEW_DATA_POINTS           1339
#define ERROR_DATA_POINTS_OUTSIDE_OF_RANGE  1340
#define ERROR_CANT_CUT_UNEVENLY_SPACED_FILE 1356
#define ERROR_DECODING_ALPHANUMERIC_FORMAT  1357
#define ERROR_MAX_NUM_FREE_FORMAT_EXCEEDED  1358
#define ERROR_MULTIPLE_X_CHANNELS_IN_FILE   1361
#define ERROR_MISSING_Y_CHANNEL_IN_FILE     1362
#define ERROR_ILLEGAL_ENUMERATED_VALUE      1365
#define ERROR_OPERATION_ON_XYZ_FILE         1378
#define ERROR_NO_FILENAME_SPECIFIED         1387
#define ERROR_REFERENCE_TIME_NOT_ZERO       1388
#define ERROR_PICK_PREFS_UNKNOWN_OPTION     1394

#define ERROR_HEADER_FILE_MISMATCH          1801
#define ERROR_BINOP_FILE_LIST_EMPTY         1803
#define ERROR_ILLEGAL_BINARY_DATA_INDEX     1804
#define ERROR_INTERPOLATE_DX_NOT_POSITIVE   2012
#define ERROR_INTERPOLATE_BEGIN_TOO_LARGE   2125

#define ERROR_SYNTAX_ERROR_IN_DO_STATEMENT  2701
#define ERROR_DO_LOOP_EXCEEDED_MAX_LENGTH   2702
#define ERROR_EVALUATING_LOGICAL_EXPRESSION 2703
#define ERROR_READING_MACRO_FILE            2704
#define ERROR_SEARCHING_MACRO_FILE_FOR      2705

#define ERROR_EXT_INTERFACE_NO_SPACE_LEFT   6010

#define ERROR_CUT_TIMES_BEYOND_DATA_LIMITS  13241325

#endif /* _ERRORS_H_ */
